# SwiftLint Configuration for FocusApp
# https://github.com/realm/SwiftLint

# ============================================================================
# PATHS
# ============================================================================

included:
  - FocusApp
  - FocusAppTests

excluded:
  - DerivedData
  - .build
  - Pods
  - Carthage
  - vendor
  - "*.generated.swift"

# ============================================================================
# ENABLED RULES
# ============================================================================

# Opt-in rules (disabled by default, explicitly enabled)
opt_in_rules:
  # Idiomatic
  - anonymous_argument_in_multiline_closure
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition
  - force_unwrapping
  - implicitly_unwrapped_optional

# ============================================================================
# DISABLED RULES
# ============================================================================

disabled_rules:
  - todo                           # Allow TODO comments during development
  - trailing_whitespace            # Can be noisy, rely on editor

# ============================================================================
# RULE CONFIGURATIONS
# ============================================================================

# Line length - warning at 120, error at 200
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

# Type body length - generous for ViewModels/Presenters
type_body_length:
  warning: 300
  error: 500

# File length - generous for view files with extensions
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Function body length (generous for async/complex functions)
function_body_length:
  warning: 60
  error: 150

# Function parameter count
function_parameter_count:
  warning: 6
  error: 8
  ignores_default_parameters: true

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

# Type name configuration
type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
  allowed_symbols: ["_"]
  validates_start_with_lowercase: error

# Identifier name configuration
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  allowed_symbols: ["_"]
  validates_start_with_lowercase: error
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k
    - n
    - to
    - at
    - by
    - ok
    - up

# Nesting - limit type and function nesting depth
nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 3
    error: 5

# Large tuple - limit tuple size
large_tuple:
  warning: 3
  error: 4

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Trailing comma - optional but recommended in multi-line collections
trailing_comma:
  mandatory_comma: false

# Force cast - warning only (sometimes necessary)
force_cast: warning

# Force try - warning only
force_try: warning

# Force unwrapping - warning only
force_unwrapping:
  severity: warning

# Implicitly unwrapped optional - warning only
implicitly_unwrapped_optional:
  severity: warning
  mode: all_except_iboutlets

# Colon spacing
colon:
  apply_to_dictionaries: true

# Comma spacing
comma: warning

# Control statement
control_statement: warning

# Opening brace spacing
opening_brace:
  ignore_multiline_function_signatures: true

# Statement position (else on same line)
statement_position:
  statement_mode: default

# Multiline parameters
multiline_parameters:
  allows_single_line: true

# Modifier order - use default order
modifier_order:
  severity: warning

# Sorted imports
sorted_imports:
  severity: warning

# Void return - prefer -> Void over -> ()
void_return: warning

# Implicit optional initialization (formerly redundant_optional_initialization)
implicit_optional_initialization: warning

# Unused closure parameter
unused_closure_parameter: warning

# Unused enumerated
unused_enumerated: warning

# ============================================================================
# CUSTOM RULES
# ============================================================================

custom_rules:
  # Avoid print statements in production code
  no_print_statements:
    name: "No Print Statements"
    regex: "\\bprint\\s*\\("
    message: "Use proper logging instead of print statements"
    severity: warning
    match_kinds:
      - identifier

  # Avoid hardcoded colors (prefer Colors.swift definitions)
  no_hardcoded_colors:
    name: "No Hardcoded Colors"
    regex: "Color\\(\\.sRGB|Color\\(red:|Color\\(hue:|#colorLiteral"
    message: "Use colors from Colors.swift instead of hardcoded values"
    severity: warning
    excluded: ".*Colors\\.swift$"

  # Require @MainActor on Presenters
  presenter_main_actor:
    name: "Presenter MainActor"
    regex: "^(final )?class \\w+Presenter(?!.*@MainActor)"
    message: "Presenters should be marked with @MainActor"
    severity: warning

  # Avoid empty catch blocks
  no_empty_catch:
    name: "No Empty Catch"
    regex: "catch\\s*\\{\\s*\\}"
    message: "Catch blocks should not be empty"
    severity: warning

  # Mark TODO with owner
  todo_with_owner:
    name: "TODO With Owner"
    regex: "//\\s*TODO(?!\\s*\\([^)]+\\):)"
    message: "TODO should include owner: // TODO(username): description"
    severity: warning

# ============================================================================
# ANALYZER RULES (requires --analyze flag)
# ============================================================================

analyzer_rules:
  - unused_import
  - unused_declaration

# ============================================================================
# REPORTER
# ============================================================================

reporter: "xcode"  # Reports in Xcode-compatible format
