# Airbnb-ish, strict-clean baseline (tune as your team needs)
# Put this at repo root: .swiftlint.yml

excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - .xcode_derived_data
  - fastlane
  - Generated
  - "**/*.generated.swift"
  - FocusAppTests
  - FocusApp/Helpers/L10n.swift
  - FocusApp/Views/CodingEnvironment/CodingEnvironmentPresenter+Snippets.swift

# Keep default rules + add high-signal opt-ins
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - sorted_imports
  - weak_delegate
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - unowned_variable_capture
  - yoda_condition
  - closure_spacing
  - no_extension_access_modifier
  - lower_acl_than_parent

# “No footguns” (make these errors in strict codebases)
force_cast: error
force_try: error
force_unwrapping: error
implicitly_unwrapped_optional: error

# Naming conventions
type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 70

identifier_name:
  min_length:
    warning: 2
    error: 1
  allowed_symbols: ["_"]
  excluded:
    - id
    - URL
    - x
    - y
    - z

# API cleanliness
function_parameter_count:
  warning: 6
  error: 8

# Complexity / size guardrails
cyclomatic_complexity:
  warning: 10
  error: 15

function_body_length:
  warning: 80
  error: 120

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 600
  error: 900
  ignore_comment_only_lines: true

line_length:
  warning: 120
  error: 160
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

nesting:
  type_level: 2
  function_level: 3

# Ban “old system” / legacy APIs with custom rules (edit this list for your team)
custom_rules:
  no_uiwebview:
    name: "No UIWebView (deprecated)"
    regex: "\\bUIWebView\\b"
    message: "Use WKWebView."
    severity: error

  no_nsurlconnection:
    name: "No NSURLConnection (legacy)"
    regex: "\\bNSURLConnection\\b"
    message: "Use URLSession."
    severity: error

  no_keywindow:
    name: "No keyWindow (multi-scene)"
    regex: "\\bkeyWindow\\b"
    message: "Use UIWindowScene / connectedScenes."
    severity: warning

  no_userdefaults_synchronize:
    name: "No UserDefaults.synchronize()"
    regex: "\\.synchronize\\(\\)"
    message: "Avoid synchronize(); it’s discouraged."
    severity: error

# Optional: extra bug-finders (run with `swiftlint analyze`)
analyzer_rules:
  - unused_import
  - unused_declaration
