import FocusNetworking

public typealias QuestionContent = FocusNetworking.QuestionContent
public typealias LeetCodeAuthSession = FocusNetworking.LeetCodeAuthSession

public typealias HTTPMethod = FocusNetworking.HTTPMethod
public typealias NetworkEndpoint = FocusNetworking.NetworkEndpoint
public typealias RequestBuilding = FocusNetworking.RequestBuilding
public typealias DefaultRequestBuilder = FocusNetworking.DefaultRequestBuilder
public typealias RequestExecuting = FocusNetworking.RequestExecuting
public typealias URLSessionRequestExecutor = FocusNetworking.URLSessionRequestExecutor

public typealias DebugLogLevel = FocusNetworking.DebugLogLevel
public typealias DebugLogCategory = FocusNetworking.DebugLogCategory
public typealias DebugLogEntry = FocusNetworking.DebugLogEntry
public typealias DebugLogRecording = FocusNetworking.DebugLogRecording
public typealias DebugLogStore = FocusNetworking.DebugLogStore

public typealias NetworkError = FocusNetworking.NetworkError
public typealias LeetCodeError = FocusNetworking.LeetCodeError
public typealias LeetCodeSubmissionError = FocusNetworking.LeetCodeSubmissionError

public typealias LeetCodeConstants = FocusNetworking.LeetCodeConstants
public typealias LeetCodeClientProtocol = FocusNetworking.LeetCodeClientProtocol
public typealias LeetCodeRestClient = FocusNetworking.LeetCodeRestClient
public typealias LeetCodeSubmissionService = FocusNetworking.LeetCodeSubmissionService
public typealias LeetCodeSubmissionCheck = FocusNetworking.LeetCodeSubmissionCheck

public typealias LeetCodeRestSubmissionListResponse = FocusNetworking.LeetCodeRestSubmissionListResponse
public typealias LeetCodeRestSubmission = FocusNetworking.LeetCodeRestSubmission
public typealias LeetCodeRestProblemResponse = FocusNetworking.LeetCodeRestProblemResponse
public typealias LeetCodeRestCodeSnippet = FocusNetworking.LeetCodeRestCodeSnippet
public typealias LeetCodeUserProfileResponse = FocusNetworking.LeetCodeUserProfileResponse
public typealias LeetCodeUserProfile = FocusNetworking.LeetCodeUserProfile
public typealias LeetCodeGraphQLResponse = FocusNetworking.LeetCodeGraphQLResponse
public typealias LeetCodeGraphQLError = FocusNetworking.LeetCodeGraphQLError
public typealias LeetCodeRecentAcSubmissionsData = FocusNetworking.LeetCodeRecentAcSubmissionsData
public typealias LeetCodeGraphQLSubmission = FocusNetworking.LeetCodeGraphQLSubmission
public typealias LeetCodeGraphQLQuestionData = FocusNetworking.LeetCodeGraphQLQuestionData
public typealias LeetCodeGraphQLQuestion = FocusNetworking.LeetCodeGraphQLQuestion
public typealias LeetCodeMetaData = FocusNetworking.LeetCodeMetaData
public typealias LeetCodeMetaParam = FocusNetworking.LeetCodeMetaParam
public typealias LeetCodeMetaReturn = FocusNetworking.LeetCodeMetaReturn
public typealias LeetCodeMetaMethod = FocusNetworking.LeetCodeMetaMethod
