import FocusData

typealias QuestionContent = FocusData.QuestionContent
typealias LeetCodeAuthSession = FocusData.LeetCodeAuthSession
typealias LeetCodeRestSubmissionListResponse = FocusData.LeetCodeRestSubmissionListResponse
typealias LeetCodeRestSubmission = FocusData.LeetCodeRestSubmission
typealias LeetCodeRestProblemResponse = FocusData.LeetCodeRestProblemResponse
typealias LeetCodeRestCodeSnippet = FocusData.LeetCodeRestCodeSnippet
typealias LeetCodeUserProfileResponse = FocusData.LeetCodeUserProfileResponse
typealias LeetCodeUserProfile = FocusData.LeetCodeUserProfile
typealias LeetCodeGraphQLResponse = FocusData.LeetCodeGraphQLResponse
typealias LeetCodeGraphQLError = FocusData.LeetCodeGraphQLError
typealias LeetCodeRecentAcSubmissionsData = FocusData.LeetCodeRecentAcSubmissionsData
typealias LeetCodeGraphQLSubmission = FocusData.LeetCodeGraphQLSubmission
typealias LeetCodeGraphQLQuestionData = FocusData.LeetCodeGraphQLQuestionData
typealias LeetCodeGraphQLQuestion = FocusData.LeetCodeGraphQLQuestion
typealias LeetCodeMetaData = FocusData.LeetCodeMetaData
typealias LeetCodeMetaParam = FocusData.LeetCodeMetaParam
typealias LeetCodeMetaReturn = FocusData.LeetCodeMetaReturn
typealias LeetCodeMetaMethod = FocusData.LeetCodeMetaMethod
